name: 'SmartCat Push'
description: 'Pushes updates for translation files into smartcat'
inputs:
  server:  # id of input
    description: 'which server to hit'
    required: false
    default: 'https://smartcat.com'
  workspace:
    description: 'workspace id'
    required: true
  projectId:
    description: 'project id'
    required: true
  apiToken:
    description: 'api token'
    required: true
  filepath:
    description: 'where to grab the english file from'
    required: true
  translationFileName:
    description: 'the name of the file to show up in the translation dashboard'
    required: false
    default: 'app'

runs:
  using: "composite"
  steps:
    - run: |
        curl "https://smartcat-cli.s3.amazonaws.com/smartcat-linux-x64.zip" -o /tmp/smartcat.zip
        unzip -q /tmp/smartcat.zip -d /usr/local/bin
        chmod +x /usr/local/bin/smartcat
      shell: sh

    - run: |
        touch smartcat.json
        echo { >> smartcat.json
        echo "server": ${{ inputs.server}}, >> smartcat.json,
        echo "workspace": ${{ inputs.workspace}}, >> smartcat.json
        echo "project": "fdfa0c4f-b08c-435f-9b57-6e54930280d3", >> smartcat.json
        echo "apiToken": "4_AKCaq7P1q2NOgrk54FD2U2tLA", >> smartcat.json
        echo } >> smartcat.json
      shell: sh
    - run: |
        smartcat import --collection=${{ inputs.translationFileName }} ${{ inputs.filepat }} --project ${{ inputs.projectId }} --language en-US -c ./smart.json
      shell: sh
    - run: |
        rm -rf smartcat.json
      shell: sh