name: Checks
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: WithAction
        uses: ./customActions/push
        with:
          workspace: ${{ secrets.WORKSPACE }}
          projectId: ${{ secrets.PROJECTID }}
          apiToken: ${{ secrets.TOKEN}}
          filepath: "./test.json" 
          translationFileName: "NEWEST"
  
     #- name: WithAction
      #  uses: ./customActions/pull
      #  with:
      #    workspace: ${{ secrets.WORKSPACE }}
      #    projectId: ${{ secrets.PROJECTID }}
      #    apiToken:  ${{ secrets.TOKEN}}
      #    languages: fr
      #    GH_TOKEN: ${{ secrets.GH_TOKEN }}
      #    outputPathPrefix: "./src/i18n/translations"