name: Checks
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build SmartCat
        - run: |
          curl "https://smartcat-cli.s3.amazonaws.com/smartcat-osx-x64.zip" -o /tmp/smartcat.zip
          unzip -q /tmp/smartcat.zip -d /usr/local/bin
          chmod +x /usr/local/bin/smartcat

        - run: smartcat

